from flask import Flask, render_template, request, redirect, url_for
from pymongo import MongoClient
import imaplib
import email
from email.header import decode_header
import google.generativeai as genai
from dotenv import load_dotenv
import os
import nltk
import re
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.tag import pos_tag


# Configure Gemini API
genai.configure(api_key="AIzaSyDuyeP_WTzAPn0-f8i5TgD8xoCwbRiBlIY")

# MongoDB configuration
client = MongoClient("mongodb://localhost:27017/")
db = client["email_data"]
collection = db["emails"]

# Initialize Flask app
app = Flask(__name__)

# Define Email class
class Email:
    def __init__(self, email_body):
        self.email_body = email_body
    
    def retrieve_email_body(self):
        return self.email_body

def summarize_and_identify_action_items(email_body):
    # Start a chat with the Generative AI model
    chat = genai.GenerativeModel("gemini-pro").start_chat()
    
    # Send the email body as input to the AI model
    val = email_body + "\n give a summary"
    response = chat.send_message(val)
    
    # Get the summary generated by the AI model
    summary = response.text
    
    # Implement logic to identify action items like schedules and deadlines
    action_items = []  # Placeholder, implement your logic here
    
    # Process the entire email body to identify action items
    # Tokenize the text into sentences
    sentences = sent_tokenize(email_body)

    # Define function to check if a word is a verb
    def is_verb(tag):
        return tag.startswith('VB')

    # Process each sentence to identify action items
    for sentence in sentences:
        # Tokenize the sentence into words
        words = word_tokenize(sentence)
        # Perform part-of-speech tagging
        tagged_words = pos_tag(words)
        # Extract verbs from tagged words as action items
        action_items.extend([word for word, tag in tagged_words if is_verb(tag)])

    return summary, action_items


def fetch_emails(username, password):
    # Connect to Gmail's IMAP server
    imap = imaplib.IMAP4_SSL("imap.gmail.com")
    imap.login(username, password)
    imap.select("inbox")

    # Search for unread emails
    result, data = imap.search(None, "UNSEEN")
    email_ids = data[0].split()

    # Fetch email bodies for each unread email
    for email_id in email_ids:
        result, data = imap.fetch(email_id, "(RFC822)")
        raw_email = data[0][1]
        msg = email.message_from_bytes(raw_email)

        # Extract email body
        body = ""
        if msg.is_multipart():
            for part in msg.walk():
                if part.get_content_type() == "text/plain":
                    body += part.get_payload(decode=True).decode("utf-8", errors="ignore")
        else:
            body = msg.get_payload(decode=True).decode("utf-8", errors="ignore")

        # Summarize email body using Gemini AI API
        summary, action_items = summarize_and_identify_action_items(body)

        # Save email to MongoDB
        email_data = {
            "subject": msg["Subject"],
            "from": msg["From"],
            "body": summary,
            "action_items": action_items,
            "unread": True,
        }
        collection.insert_one(email_data)

        # Mark email as read
        imap.store(email_id, "+FLAGS", "\\Seen")

    # Close the connection
    imap.close()
    imap.logout()

@app.route("/")
def index():
    return redirect(url_for("login"))

@app.route("/login")
def login():
    return render_template("login.html")

@app.route("/submit", methods=["POST"])
def submit():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        # Fetch emails
        fetch_emails(email, password)

        return redirect(url_for("dashboard"))
    else:
        return "Method Not Allowed", 405

@app.route("/dashboard")
def dashboard():
    try:
        # Fetch only unread emails from MongoDB and convert to a list
        unread_emails = list(collection.find({"unread": True}))

        # Render the dashboard template with the emails data
        return render_template("dashboard.html", emails=unread_emails)
    except Exception as e:
        # Log the error and render an error template or return a generic error message
        print(f"Error occurred: {e}")
        return "An error occurred while fetching data for the dashboard.", 500

if __name__ == "__main__":
    app.run(debug=True)
